### PR TITLE
[WIP] Adapt changes to upstream embassy-net

### PR DESCRIPTION
**Pull request by showier-drastic**
Commit https://github.com/embassy-rs/embassy/commit/be0d9775e3bcc3c1bd1448e357d7c6cd67b68991 made a rather large change to lifetime/generics semantics to embassy-net. Update edge-nal-embassy to adapt to it.

Tested to compile, but not tested to run yet.

### CODE REVIEW

**Comment by ivmarkov** [comment]
Yes - thank you!

I think we should wait for [this PR](https://github.com/embassy-rs/embassy/pull/3397) to get merged as well, as it will bring even more changes to `embassy-net` (it will switch to the `core::net` types). 

Given that the upstream PR that switches `smoltcp` to `core::net` types already got merged, I don't think the `embassy-net` one would be delayed by a lot, if at all.

**Comment by ivmarkov** [comment]
Also - you need to run `cargo fmt`

**Comment by AnthonyGrondin** [comment]
Both PRs have been merged, so feel free to continue this PR with the needed changes.

Smoltcp and embassy-net haven't had a release yet, at the time of writing this, but we can get by with using patches, I believe.

**Comment by showier-drastic** [comment]
> Both PRs have been merged, so feel free to continue this PR with the needed changes.
> 
> Smoltcp and embassy-net haven't had a release yet, at the time of writing this, but we can get by with using patches, I believe.

Nice to hear that, I will update this PR hopefully in a day or two.

**Comment by showier-drastic** [comment]
Hi @AnthonyGrondin ,

It is not clear to me how to implement `readable` and `writable`.

For example, for `edge_nal_embassy::tcp::TcpSocketRead` you only have `embassy_net::tcp::TcpReader` inside it; however, in order to call `wait_read_ready`, you need `embassy_net::tcp::TcpSocket`.

Maybe we should add `wait_read_ready` to `embassy_net::tcp::TcpReader` (and the counterpart for Writer & Udp)?

I'd appreciate it if you could give some suggestions.

**Comment by AnthonyGrondin** [comment]
I'm not sure if it's a hard requirement to implement `readable` for `edge_nal_embassy::tcp::TcpSocketRead` at the moment.

As long as it's implemented for `TcpSocket` and `UdpSocket`. For `edge_nal_embassy::tcp::TcpSocketRead`, it might require more changes to be upstreamed into embassy-net.

@ivmarkov Can comment more on that.

**Comment by ivmarkov** [comment]
Yes, this is an omission. TcpSocketRead should also have `wait_read_ready`, and the other way around, for `TcpSocketWrite`.

**Comment by ivmarkov** [comment]
And btw same for the UDP socket splits.

**Comment by showier-drastic** [comment]
It seems that we don't have a `Writable` trait, so there's no writable for writers.

**Comment by ivmarkov** [comment]
> It seems that we don't have a `Writable` trait, so there's no writable for writers.

Yes, but regardless of that having `wait_write_ready` on `TcpWriter` still makes a lot of sense, outside of `edge-nal-embassy` and for the cases when you use `embassy-net` directly.

**Comment by ivmarkov** [comment]
@showier-drastic [this PR](https://github.com/embassy-rs/embassy/pull/3485) just got merged, so if you would like to resume your work here, I think all obstacles should hopefully be cleared by now. :)

Thanks to @AnthonyGrondin

**Comment by ivmarkov** [comment]
We can branch the repo and merge it earlier.

**Comment by ivmarkov** [comment]
Superceded by https://github.com/ivmarkov/edge-net/pull/49

**Pull request closed without merging**
